name: Release2

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build Binaries
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            targets: linux-amd64,linux-arm64,windows-amd64
          - os: macos-latest
            targets: darwin-amd64,darwin-arm64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install cross-compilation tools
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu gcc-mingw-w64-x86-64

      - name: Get build info
        id: build_info
        run: |
          echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "build_date=$(date -u +%Y-%m-%d)" >> $GITHUB_OUTPUT
          echo "release_name=$(date -u +%Y-%m-%d)-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build binaries
        env:
          COMMIT_HASH: ${{ steps.build_info.outputs.commit_hash }}
          BUILD_DATE: ${{ steps.build_info.outputs.build_date }}
        run: |
          mkdir -p dist

          if [[ "${{ runner.os }}" == "Linux" ]]; then
            # Linux amd64
            GOOS=linux GOARCH=amd64 CGO_ENABLED=1 \
              CGO_CFLAGS="-DSQLITE_ENABLE_FTS5" \
              CGO_LDFLAGS="-lm" \
              go build -ldflags "-X main.Version=${COMMIT_HASH} -X main.BuildDate=${BUILD_DATE}" \
              -o dist/github-brain-linux-amd64

            # Linux arm64
            GOOS=linux GOARCH=arm64 CGO_ENABLED=1 CC=aarch64-linux-gnu-gcc \
              CGO_CFLAGS="-DSQLITE_ENABLE_FTS5" \
              CGO_LDFLAGS="-lm" \
              go build -ldflags "-X main.Version=${COMMIT_HASH} -X main.BuildDate=${BUILD_DATE}" \
              -o dist/github-brain-linux-arm64

            # Windows amd64
            GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc \
              CGO_CFLAGS="-DSQLITE_ENABLE_FTS5" \
              CGO_LDFLAGS="-lm" \
              go build -ldflags "-X main.Version=${COMMIT_HASH} -X main.BuildDate=${BUILD_DATE}" \
              -o dist/github-brain-windows-amd64.exe
          else
            # macOS amd64
            GOOS=darwin GOARCH=amd64 CGO_ENABLED=1 \
              CGO_CFLAGS="-DSQLITE_ENABLE_FTS5" \
              go build -ldflags "-X main.Version=${COMMIT_HASH} -X main.BuildDate=${BUILD_DATE}" \
              -o dist/github-brain-darwin-amd64

            # macOS arm64
            GOOS=darwin GOARCH=arm64 CGO_ENABLED=1 \
              CGO_CFLAGS="-DSQLITE_ENABLE_FTS5" \
              go build -ldflags "-X main.Version=${COMMIT_HASH} -X main.BuildDate=${BUILD_DATE}" \
              -o dist/github-brain-darwin-arm64
          fi

      - name: Create archives
        env:
          COMMIT_HASH: ${{ steps.build_info.outputs.commit_hash }}
        run: |
          cd dist

          if [[ "${{ runner.os }}" == "Linux" ]]; then
            # Linux archives
            tar -czf github-brain-${COMMIT_HASH}-linux-amd64.tar.gz github-brain-linux-amd64
            tar -czf github-brain-${COMMIT_HASH}-linux-arm64.tar.gz github-brain-linux-arm64

            # Windows archive
            zip github-brain-${COMMIT_HASH}-windows-amd64.zip github-brain-windows-amd64.exe

            # Clean up binaries
            rm github-brain-linux-* github-brain-*.exe
          else
            # macOS archives
            tar -czf github-brain-${COMMIT_HASH}-darwin-amd64.tar.gz github-brain-darwin-amd64
            tar -czf github-brain-${COMMIT_HASH}-darwin-arm64.tar.gz github-brain-darwin-arm64

            # Clean up binaries
            rm github-brain-darwin-*
          fi

      - name: Generate checksums
        run: |
          cd dist
          sha256sum *.tar.gz *.zip > SHA256SUMS.txt 2>/dev/null || shasum -a 256 *.tar.gz *.zip > SHA256SUMS.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ runner.os }}
          path: dist/*

  release:
    name: Create Releases
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get build info
        id: build_info
        run: |
          echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "build_date=$(date -u +%Y-%m-%d)" >> $GITHUB_OUTPUT
          echo "release_name=$(date -u +%Y-%m-%d)-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: binaries-*
          merge-multiple: true

      - name: Create Archived Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.build_info.outputs.release_name }}
          name: ${{ steps.build_info.outputs.release_name }}
          body: |
            Built from commit `${{ steps.build_info.outputs.commit_hash }}` on ${{ steps.build_info.outputs.build_date }}

            **Download:**
            - macOS (Intel): `github-brain-${{ steps.build_info.outputs.commit_hash }}-darwin-amd64.tar.gz`
            - macOS (Apple Silicon): `github-brain-${{ steps.build_info.outputs.commit_hash }}-darwin-arm64.tar.gz`
            - Linux (x86_64): `github-brain-${{ steps.build_info.outputs.commit_hash }}-linux-amd64.tar.gz`
            - Linux (ARM64): `github-brain-${{ steps.build_info.outputs.commit_hash }}-linux-arm64.tar.gz`
            - Windows: `github-brain-${{ steps.build_info.outputs.commit_hash }}-windows-amd64.zip`

            Verify with `SHA256SUMS.txt`
          files: |
            dist/*.tar.gz
            dist/*.zip
            dist/SHA256SUMS.txt
          draft: false
          prerelease: false

      - name: Update Latest Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest
          body: |
            **Latest build:** `${{ steps.build_info.outputs.commit_hash }}` from ${{ steps.build_info.outputs.build_date }}

            This release always points to the most recent build. For archived releases, see [all releases](https://github.com/wham/github-brain/releases).

            **Quick install:**
            ```bash
            # macOS Apple Silicon
            curl -L https://github.com/wham/github-brain/releases/latest/download/github-brain-${{ steps.build_info.outputs.commit_hash }}-darwin-arm64.tar.gz | tar xz

            # macOS Intel
            curl -L https://github.com/wham/github-brain/releases/latest/download/github-brain-${{ steps.build_info.outputs.commit_hash }}-darwin-amd64.tar.gz | tar xz

            # Linux x86_64
            curl -L https://github.com/wham/github-brain/releases/latest/download/github-brain-${{ steps.build_info.outputs.commit_hash }}-linux-amd64.tar.gz | tar xz

            # Windows (in PowerShell)
            Invoke-WebRequest https://github.com/wham/github-brain/releases/latest/download/github-brain-${{ steps.build_info.outputs.commit_hash }}-windows-amd64.zip -OutFile github-brain.zip
            ```
          files: |
            dist/*.tar.gz
            dist/*.zip
            dist/SHA256SUMS.txt
          draft: false
          prerelease: false
          make_latest: true
